return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "stylua",
      "shellcheck",
      "shfmt",
      "flake8",
      "astro-language-server",
      "typescript-language-server",
      "html-lsp",
      "emmet-language-server",
      "css-lsp",
      "cssmodules-language-server",
      "tailwindcss-language-server",
      "lua-language-server",
      "prisma-language-server",
      "json-lsp",
      "svelte-language-server",
      "vue-language-server",
      "angular-language-server",
      "rust-analyzer",
      "prettier",
      "vue-language-server",
      "zls",
    },
  },
}
